### ISSUE TITLE
DevWorkspaceRouting reconciler breaks endpoints when they specify a path

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#1031]
### Description
The DevWorkspaceRouting reconciler does not correctly handle endpoints that specify a path, resulting in a mismatch between the route/ingress created and the endpoint reported the DevWorkspace reconciler. This can result in workspaces failing to start, if an affected endpoint is marked as the 'main' one.

### How To Reproduce
Apply the following workspace:
```yaml
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: plain-devworkspace
spec:
  started: true
  routingClass: 'basic'
  template:
    components:
      - name: web-terminal
        container:
          image: quay.io/wto/web-terminal-tooling:next
          memoryLimit: 512Mi
          mountSources: true
          command:
            - "tail"
            - "-f"
            - "/dev/null"
          endpoints:
            - name: test-path
              targetPort: 8890
              exposure: public
              path: /test/path/
              protocol: http
            - name: test-no-path
              targetPort: 8890
              exposure: public
              protocol: http
```
This creates routes, e.g.:
```
NAME                                        HOST/PORT                                     PATH                SERVICES                            PORT    TERMINATION     WILDCARD
workspace7d8fbdb0fae242e7-test-no-path      workspace7d8fbdb0fae242e7.<cluster-url>.com   /test-no-path/      workspace7d8fbdb0fae242e7-service   8890    edge/Redirect   None
workspace7d8fbdb0fae242e7-test-path         workspace7d8fbdb0fae242e7.<cluster-url>.com   /test-path/         workspace7d8fbdb0fae242e7-service   8890    edge/Redirect   None
```

however the DevWorkspaceRouting gets a status like
```yaml
  exposedEndpoints:
    web-terminal:
    - name: test-path
      # Should be http://workspace7d8fbdb0fae242e7.<cluster-url>.com/test-path/test/path/
      url: http://workspace7d8fbdb0fae242e7.<cluster-url>.com/test/path/
    - name: test-no-path
      url: http://workspace7d8fbdb0fae242e7.<cluster-url>.com/test-no-path/
```
