### ISSUE TITLE
starterProjects support

### ISSUE THREAD

**Issue by l0rd** [devfile/devworkspace-operator#1084]
### Description

`starterProjects` are currently ignored by the DevWorkspace operator as there is no interaction with the developer.

But if a client, like the Che dashboard, allow the developer to chose one `starterProject`, then the choice should be specified in the DW object so that the DWO can use it as that CR project. For that we can introducing `spec.selectedStarterProject`:

```yaml
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
spec:
  selectedStarterProject: project-1 
  template:
    starterProjects:
      - name: project-1
        git:
           (...)
```

### Additional context

This work should be part of the epic to support `registry.devfile.io`: https://github.com/eclipse/che/issues/20251
