### ISSUE TITLE
Project clone does not respect additional certificates when querying remotes

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#1114]
### Description
When attempting to clone a repository that uses self-signed (or otherwise default-untrusted) certificates fails even if additional CA certs are available.

The project clone container successfully clones the repository, suggesting that steps that delegate to the `git` binary do include the additional certificates. However, setting up the project fails when attempting to query remotes to determine if the specificed `checkoutFrom.revision` is a branch, tag, or hash.

### How To Reproduce
Create a DevWorkspace with a project that uses a self-signed repository. This project should specify the `checkoutFrom` field:

```yaml
spec:
  template:
    projects: 
      - name: selfsigned
        git: 
          remotes: 
            origin: "<selfsigned-repository>"
          checkoutFrom: 
            revision: main
```

### Expected behavior
Since we're able to clone the project, there should be no issue checking out the specified reference.
