### ISSUE TITLE
Mounting an automount configmap as subpath ignores binaryData field

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#1155]
### Description
Mounting a configmap with `.binaryData` and `controller.devfile.io/mount-as: subpath` ignores keys in `binaryData`

### How To Reproduce
Create a configmap 
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: test-cm
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-configmap: 'true'
  annotations:
    controller.devfile.io/mount-as: subpath
    controller.devfile.io/mount-path: /tmp/
binaryData:
  testfile: aGVsbG8K # "hello"
```
and note that `testfile` is not mounted to `/tmp/testfile`

### Expected behavior
Subpath mounts should consider both binaryData and data.
