### ISSUE TITLE
Webhook Server Certificate

### ISSUE THREAD

**Issue by bdwyertech** [devfile/devworkspace-operator#1157]
### Description
Seems like the webhook server is not getting restarted when cert-manager issues a new certificate.  I would expect the `devworkspace-controller-manager` to do this, or for the webhook server to see that the cert has been rolled.

Perhaps I just have something misconfigured, but when this cert expires, it causes issues for other non-devworkspace pods.  Killing the webhook server and letting a new pod come up resolves the issue.

I am using the following Flux config:
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: devworkspace-operator
  namespace: devworkspace-controller
spec:
  interval: 1h
  url: https://github.com/devfile/devworkspace-operator
  ref:
    tag: v0.22.0
  ignore: |
    # exclude all
    /*
    # include k8s deploy objects directory
    !/deploy/deployment/kubernetes/objects/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: devworkspace-operator
  namespace: devworkspace-controller
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: devworkspace-operator
  path: ./deploy/deployment/kubernetes/objects
  prune: true
```
