### ISSUE TITLE
Per workspace PVC size calculation can abort early and miss some volumes

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#1162]
### Description
In computing the per-workspace PVC size, the following rules are supposed to be used

* If all volumes in a devworkspace specify their size, the computed PVC size will be used.
* If all volumes in a devworkspace either specify their size or are ephemeral, the computed PVC size will be used.
* If at least one volume in a devworkspace specifies its size, and the computed PVC size is greater than the default per-workspace PVC size, the computed PVC size will be used.

However, in some cases, the third option is followed, as collecting all defined PVC sizes exits early after encountering a volume that does not define a size.

### How To Reproduce
It depends on iteration order for PVC volumes, though the following DevWorkspace should reproduce
```yaml
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: plain-devworkspace
spec:
  started: true
  routingClass: 'basic'
  template:
    components:
      - name: web-terminal
        container:
          image: quay.io/wto/web-terminal-tooling:next
          memoryRequest: 256Mi
          memoryLimit: 512Mi
          mountSources: true
          command:
           - "tail"
           - "-f"
           - "/dev/null"
          volumeMounts:
            - name: no-size-volume
              path: /home/user/no-size-volume
            - name: sized-volume
              path: /home/user/sized-volume
      - name: no-size-volume
        volume: {}
      - name: sized-volume
        volume:
          size: 10Gi
```
(we would expect the per-workspace PVC to be 10Gi instead of the default 5Gi here)

### Additional context
Original PR: https://github.com/devfile/devworkspace-operator/pull/1020
Related issue: https://issues.redhat.com/browse/CRW-4609
