### ISSUE TITLE
persistentHome volume name should not use upper-case letters

### ISSUE THREAD

**Issue by AObuchow** [devfile/devworkspace-operator#1200]
If the DWOC's `workspace.persistUserHome: true` field is set, then a devfile volume [named](https://github.com/devfile/devworkspace-operator/blob/b512c88f908d08558da6ee9750814c08714f1a4a/pkg/constants/constants.go#L42) `persistentHome` will be injected into the devworkspace. The name of this volume should not include any upper-case letters, as this would be an invalid devfile component volume name (i.e. it doesn't match the following [regex](https://github.com/devfile/api/blob/b4fea572af1a98ca487495857add4007c35f5aea/pkg/apis/workspaces/v1alpha2/components.go#L49)).

For example, the following devworkspace would fail to start due to kubebuilder/webhook validation:

```YAML
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: plain-devworkspace
spec:
  started: true
  routingClass: 'basic'
  template:
    components:
      - name: web-terminal
        container:
          image: quay.io/wto/web-terminal-tooling:next
          memoryRequest: 256Mi
          memoryLimit: 512Mi
          mountSources: true
          command:
           - "tail"
           - "-f"
           - "/dev/null"
          volumeMounts:
            - name: persistentHome
              path: /home/user/
      - name: persistentHome
        volume: {}
```

However, when persistUserHome is enabled in DWO, the devworkspace object will contain a volume named `persistentHome`.

 The persistentHome volume should instead be renamed to `persistent-home`.
