### ISSUE TITLE
Missing operatorframework.io/arch label in DWO CSV

### ISSUE THREAD

**Issue by AObuchow** [devfile/devworkspace-operator#1227]
### Description
Currently, installing DevWorkspace Operator through OLM is impossible on architectures other than amd64. This is because the `operatorframework.io/arch.[arm64,ppc64le,s390x]: supported` label is missing the clusterserviceversion (see [here](https://olm.operatorframework.io/docs/advanced-tasks/ship-operator-supporting-multiarch/#multiple-architectures) and [here](https://sdk.operatorframework.io/docs/advanced-topics/multi-arch/) for more info on multi-arch  Operators).

### How To Reproduce
1. Get access to a PPC, IBM Z or arm64 OpenShift Cluster (cluster bot allows for arm64)
2. From the DWO repo, run `make register_catalogsource`
3. Visit OperatorHub
4. See that DevWorkspace Operator is not available in OperatorHub
5. If you go to the DWO PackageManifest of DWO, you'll see that only amd64 is supported (which is the default value that is automatically set by the Operator Framework)

```YAML
(...)
  labels:
    catalog: devworkspace-operator-catalog
    catalog-namespace: openshift-marketplace
    operatorframework.io/arch.amd64: supported
    operatorframework.io/os.linux: supported
    provider: Devfile
    provider-url: 'https://devfile.io'
```

### Expected behavior
DWO should be installable on s390x, arm64 and ppc64le clusters.

### Additional context
[Downstream issue](https://issues.redhat.com/browse/CRW-5662)
