### ISSUE TITLE
extension management in declarative way 

### ISSUE THREAD

**Issue by yaroslavkasatikov** [devfile/devworkspace-operator#1262]
Hi team,
Could you please tell me or share the link with the way how to add extension declarative in devoperator managed dev workspace?

Thanks a lot!

**Comment by AObuchow** [comment]
Sorry, can you provide some more detail on what you're looking for? What kind of extensions are you referring to? What are you trying to accomplish? Thanks.

**Comment by yaroslavkasatikov** [comment]
Hey @AObuchow,
Thank you for the reply.

For example I want to add .vscode/extension like:

```
  attributes:
    .vscode/extensions.json: |
      {
        "recommendations": [
          "redhat.java"
        ]
      }
```
I want to do it declarative in DevWorkspace resource, but can't find the way :(

**Comment by AObuchow** [comment]
@yaroslavkasatikov This is not currently possible from my knowledge, though maybe some hacky workaround exists that I haven't thought of yet.

From my understanding, the supported way to add a `.vscode/extension` is to include it in your devfile's repository, like [this for example](https://github.com/eclipse-che/che-operator/blob/main/.vscode/extensions.json). Could you let me know if that solution fit your needs?

**Comment by yaroslavkasatikov** [comment]
Okay, got it! 
Do you know if the devworkspace-operator has the ability to mount configMap inside the container?
This way the extensions may be mounted into project dir..

**Comment by AObuchow** [comment]
@yaroslavkasatikov yes, you can configure configmaps with data that is automatically mounted to all your devworkspaces, see [here](https://github.com/devfile/devworkspace-operator/blob/main/docs/additional-configuration.adoc#automatically-mounting-volumes-configmaps-and-secrets).

You'll likely need to use `controller.devfile.io/mount-as: subpath` since the` /projects/` directory already exists. Here's an example of how this configmap would look like. Note that you'll have to set the appropriate namespace and project directory name:

```YAML
kind: ConfigMap
apiVersion: v1
metadata:
  name: code-extensions
  namespace: <your-devspaces-user-namespace>
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-configmap: 'true'
  annotations:
    controller.devfile.io/mount-as: subpath
    controller.devfile.io/mount-path: /projects/<your-project-name>/.vscode/
data:
  extensions.json: |
      {
        "recommendations": [
          "redhat.java"
        ]
      }
```

The disadvantage of this approach is that the same configmap will be mounted in all of your devworkspaces, and each devworkspace will probably have a different name for your project (thus, the mount-path will only be valid for a single devworkspace). 

I guess theoretically, you could mount your `extensions.json` somewhere other than your project location, and then have a [preStart command](https://devfile.io/docs/2.2.2/devfile-schema#events-post-start) that does a `mkdir $PROJECT_SOURCE/.vscode/` and `cp <path-to-extensions.json> $PROJECT_SOURCE/.vscode/extensions.json`.

It'd be nice if we could set `controller.devfile.io/mount-path: /projects/$PROJECT_SOURCE/.vscode/` but unfortunately the $PROJECT_SOURCE environment variable (which points to your active devfile project) won't be expanded properly. This could be a useful feature to request?
