### ISSUE TITLE
Valid commands in devworkspaces using devfile validation package

### ISSUE THREAD

**Issue by AObuchow** [devfile/devworkspace-operator#1336]
### Description
The devfile API provides a validation package that can be used to [validate devfile commands](https://github.com/devfile/api/blob/7afd63f5e52e3ca77837bb452bbe1e34fa69ee5f/pkg/validation/commands.go#L31). 

We should use this to validate the commands present in a devworkspace during the devworkspace reconciliation. We should also use this validation in the validating webhook. 

Not only would this catch invalid devfile's provided by users, but it would prevent any errors when DWO injects invalid commands into the devworkspace, as was mentioned in https://github.com/devfile/devworkspace-operator/pull/1329#issuecomment-2427465686 where commands with the same ID were being injected into the devworkspace.

Currently, the following devworkspace will be start, despite having 2 commands with the same ID:

```YAML
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: code-latest-duplicate-commands
spec:
  started: true
  template:
    attributes:
        controller.devfile.io/storage-type: ephemeral
    projects:
      - name: web-nodejs-sample
        git:
          remotes:
            origin: "https://github.com/che-samples/web-nodejs-sample.git"
    commands:
      - id: say-hello
        exec:
          component: che-code-runtime-description
          commandLine: echo "Hello from $(pwd)"
          workingDir: ${PROJECT_SOURCE}/app
      - id: say-hello
        exec:
          component: che-code-runtime-description
          commandLine: echo "Second hello from $(pwd)"
          workingDir: ${PROJECT_SOURCE}/app
  contributions:
    - name: che-code
      uri: https://eclipse-che.github.io/che-plugin-registry/main/v3/plugins/che-incubator/che-code/latest/devfile.yaml
      components:
        - name: che-code-runtime-description
          container:
            env:
              - name: CODE_HOST
                value: 0.0.0.0
```

I'd expect the above devworkspace to fail, citing commands with duplicate IDs (which is not permitted by the [devfile API](https://devfile.io/docs/2.3.0/devfile-validation-rules)).
