### ISSUE TITLE
SSH agent initialization postStart event fails workspace if $HOME is not writable

### ISSUE THREAD

**Issue by AObuchow** [devfile/devworkspace-operator#1337]
### Description
In container images where the $HOME directory is not writable (such as the [go-toolset image](https://catalog.redhat.com/software/containers/ubi9/go-toolset/61e5c00b4ec9945c18787690?q=go-toolset&architecture=amd64&image=671a510d619d7bdd5e9631a0), which has `$HOME=/opt/app-root/src/`) the `init-ssh-agent-command-...` postStart event will fail. 

This is due to the fact we assume `$HOME/ssh-environment` is writable when [doing](https://github.com/devfile/devworkspace-operator/blob/ff723835cc3ed38c9f8a5fbf36dcfddf1890ac9c/pkg/library/ssh/event.go#L26) `ssh-agent | sed 's/^echo/#echo/' > $SSH_ENV_PATH`, however this is not always the case:
```bash
$ ssh-agent |  sed 's/^echo/#echo/' > $SSH_ENV_PATH
bash: /opt/app-root/src/ssh-environment: Permission denied
```

Maybe we should wrap the entire ssh-agent intialization command with a `(...) || true` so that regardless of wether a specific step of the ssh-agent initialization fails, the workspace will start up. This is the approach taken for the `init-persistent-home` [preStart even](https://github.com/devfile/devworkspace-operator/blob/ff723835cc3ed38c9f8a5fbf36dcfddf1890ac9c/pkg/library/home/persistentHome.go#L30-L46)t.

### How To Reproduce
1. [Set up an SSH key with a passphrase](https://github.com/devfile/devworkspace-operator/blob/main/docs/additional-configuration.adoc#configuring-devworkspaces-to-use-ssh-keys-for-git-operations) 
2. Create a workspace using the go-toolset image:

```YAML
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: plain-devworkspace
spec:
  started: true
  routingClass: 'basic'
  template:
    components:
      - name: web-terminal
        container:
          image: registry.access.redhat.com/ubi9/go-toolset:1.19.13-4.1697647145
          memoryRequest: 256Mi
          memoryLimit: 512Mi
          mountSources: true
          command:
           - "tail"
           - "-f"
           - "/dev/null"
```

3. Check the workspace status, it should have failed: `oc get devworkspace -n $NAMESPACE`
 
### Expected behavior
The workspace should succceed to start up. Whether the automatic SSH passphrase provisioning functionality works is another topic (maybe we should set `SSH_ENV_PATH=/tmp/ssh-environment` instead of `SSH_ENV_PATH=$HOME/ssh-environment`?)

### Additional context
[Upstream Che Issue](https://github.com/eclipse-che/che/issues/23213)

**Comment by l0rd** [comment]
@AObuchow I have the same issue but that's not related to `$HOME` not being writable, in my case, the second container is distroless so it doesn't have `sh` or `true`. Any postStart event will fail in that container. But the `init-ssh-agent-command` is injected in both containers.

Some ideas:
1. There should be a documented attribute to opt-out from post start events
2. If there are multiple components the event should be added for the first component only
3. If `mountSources: false` there should be no need to add the `init-ssh-agent-command-...` postStart event

That's my DevWorkspace with 2 containers:

```yaml
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: outyet-dw
spec:
  contributions:
    - components:
        - container:
            env:
              - name: CODE_HOST
                value: 0.0.0.0
          name: che-code-runtime-description
      name: che-code
      uri: https://eclipse-che.github.io/che-plugin-registry/main/v3/plugins/che-incubator/che-code/latest/devfile.yaml
  started: true
  template:
    components:
      - container:
          image: ghcr.io/l0rd/outyet-dev:latest
          memoryRequest: 2G
          memoryLimit: 10G
          cpuRequest: '1'
          cpuLimit: '4'
          mountSources: true
        name: dev
      - container:
          cpuLimit: 500m
          image: ghcr.io/l0rd/outyet:latest
          memoryLimit: 128Mi
          mountSources: false
        name: outyet
    projects:
      - git:
          remotes:
            origin: https://github.com/l0rd/outyet.git
        name: outyet
        sourceType: Git
```
