### ISSUE TITLE
Allow configuring memory and CPU request / limits  

### ISSUE THREAD

**Issue by ibuziuk** [devfile/devworkspace-operator#1343]
### Description
Currently, it is not possible to configure memory and CPU for DWO pod. The only workaround is patching CSV directly, but since the CSV gets replaced as part of an upgrade, the modified value gets reverted to the older default values e.g. for devworkspace-controller-manager
```
              spec:
                containers:
                  - resources:
                      limits:
                        cpu: '3'
                        memory: 3Gi
                      requests:
                        cpu: 250m
                        memory: 100Mi
```

### Additional context
Need to investigate if we can propagate RAM / CPU configuration from the subscription directly and if it is a good approach in general - https://developers.redhat.com/articles/2023/03/06/5-global-environment-variables-provided-openshift-gitops#

**Comment by ibuziuk** [comment]
@dkwon17 @AObuchow please, review

**Comment by dkwon17** [comment]
As discussed, it's possible to set the memory and CPU limits of the DWO pod in the `Subscription`: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/subscription-config.md

Example:
```
spec:
  channel: fast
  installPlanApproval: Automatic
  name: devworkspace-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: devworkspace-operator.v0.31.1
  config:
    resources:
      limits:
        memory: "4Gi"
```

However, the resource limits are applied to all containers (2) in the pod, and not just the `devworkspace-controller` containers. Since there are two containers, the total memory limit for the configuration above is 8Gi
