### ISSUE TITLE
DWOC config.workspace.containerSecurityContext not being applied to containers added via routingClass

### ISSUE THREAD

**Issue by dkwon17** [devfile/devworkspace-operator#1359]
### Description

When the DWOC defines a `containerSecurityContext`:
```
    containerSecurityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
          - SETGID
          - SETUID
```

the `containerSecurityContext` is not applied to the workspace containers that are added via routing class.

This behaviour is most easily reproduced with Eclipse Che (which uses the `che` routing class), see https://github.com/eclipse-che/che/issues/22747.

In the case of Eclipse Che, the workspace container that does not have the `containerSecurityContext` set, is the `che-gateway` conatiner.

### Expected behavior

The  `containerSecurityContext`  should be applied to all workspace containers
