### ISSUE TITLE
Web Terminal Tooling depends on injecting kubeconfig into the first available container

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#258]
## Description

The Web Terminal Tooling plugin handles `/exec/init` calls by attempting to inject kubeconfig into [the first container in the pod](https://github.com/eclipse/che-machine-exec/blob/07cb90b2079b8577fad2d0d16cdb736096aea75b/exec/kubernetes_exec_manager.go#L107). If this fails, the whole call fails, so the plugin only works when the tooling container is first in the list.

However, the devfile/api functions for [merging plugin components](https://github.com/devfile/api/blob/6424f4139ac7f3d535cfa97084f5612cd78a1226/pkg/utils/overriding/merging.go#L28-L35) into a devworkspace merge components in the order 1. Parent, 2. Plugins, 3. Main content, resulting in the tooling container being last in the list. This causes web terminal to fail with changes from https://github.com/devfile/devworkspace-operator/pull/240

## Short-term solution
The web terminal should resolve the _first_ compatible container (i.e. if it can't resolve an exec in the first container, it should try the second, etc.)

## Long-term solution
We need a way of specifying where web terminal should inject kubeconfig.

**Comment by amisevsk** [comment]
A more isolated test: using the current master branch and the `flattened_web-terminal.yaml` sample, switching the order of components causes web terminal to fail on `crc`:

Works:
```yaml
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: web-terminal
  annotations:
    controller.devfile.io/restricted-access: "true"
  labels:
    # it's a label OpenShift console uses a flag to mark terminal's workspaces
    console.openshift.io/terminal: "true"
spec:
  started: true
  routingClass: 'web-terminal'
  template:
    components:
      # TODO: Remove once defaulting for web terminal is implemented.
      - name: dev
        container:
          image: quay.io/wto/web-terminal-tooling:latest
          mountSources: false
          memoryLimit: 256Mi
          args: ["tail", "-f", "/dev/null"]
          env:
            - value: '\[\e[34m\]>\[\e[m\]\[\e[33m\]>\[\e[m\]'
              name: PS1
      - name: web-terminal
        container:
          image: quay.io/eclipse/che-machine-exec:nightly
          mountSources: false
          command: ["/go/bin/che-machine-exec",
                    "--authenticated-user-id", "$(DEVWORKSPACE_CREATOR)",
                    "--idle-timeout", "$(DEVWORKSPACE_IDLE_TIMEOUT)",
                    "--pod-selector", "controller.devfile.io/workspace_id=$(CHE_WORKSPACE_ID)",
                    "--use-bearer-token",
                    "--use-tls"]
          endpoints:
            - name: web-terminal
              targetPort: 4444
              attributes:
                protocol: http
                type: ide
                discoverable: "false"
                secure: "true"
                cookiesAuthEnabled: "true"
          env:
            - name: USE_BEARER_TOKEN
              value: "true"
```

Does not work:
```yaml
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: web-terminal
  annotations:
    controller.devfile.io/restricted-access: "true"
  labels:
    # it's a label OpenShift console uses a flag to mark terminal's workspaces
    console.openshift.io/terminal: "true"
spec:
  started: true
  routingClass: 'web-terminal'
  template:
    components:
      - name: web-terminal
        container:
          image: quay.io/eclipse/che-machine-exec:nightly
          mountSources: false
          command: ["/go/bin/che-machine-exec",
                    "--authenticated-user-id", "$(DEVWORKSPACE_CREATOR)",
                    "--idle-timeout", "$(DEVWORKSPACE_IDLE_TIMEOUT)",
                    "--pod-selector", "controller.devfile.io/workspace_id=$(CHE_WORKSPACE_ID)",
                    "--use-bearer-token",
                    "--use-tls"]
          endpoints:
            - name: web-terminal
              targetPort: 4444
              attributes:
                protocol: http
                type: ide
                discoverable: "false"
                secure: "true"
                cookiesAuthEnabled: "true"
          env:
            - name: USE_BEARER_TOKEN
              value: "true"
      # TODO: Remove once defaulting for web terminal is implemented.
      - name: dev
        container:
          image: quay.io/wto/web-terminal-tooling:latest
          mountSources: false
          memoryLimit: 256Mi
          args: ["tail", "-f", "/dev/null"]
          env:
            - value: '\[\e[34m\]>\[\e[m\]\[\e[33m\]>\[\e[m\]'
              name: PS1
```
