### ISSUE TITLE
It should be possible to start a devworkspace without IDE

### ISSUE THREAD

**Issue by sleshchenko** [devfile/devworkspace-operator#274]
It should be possible to start a devworkspace without IDE, like the following:

```yaml
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: java-sample
spec:
  started: true
  template:
    projects:
      - name: frontend
        git:
          remotes:
            origin: https://github.com/spring-projects/spring-petclinic
    components:
    - name: maven
      container:
        image: quay.io/eclipse/che-java8-maven:nightly
```
