### ISSUE TITLE
Deployment Fails To Start When DW Is Updated To Use Terminal Plugin

### ISSUE THREAD

**Issue by tinakurian** [devfile/devworkspace-operator#341]
Steps to Reproduce:
- create DW with dev terminal plugin
- update DW to use terminal plugin
- deployment is not started due missing certificates for machine-exec. I assume service does not get annotations provided

**Comment by tinakurian** [comment]
The error:
```
[GIN-debug] [ERROR] open /var/serving-cert/tls.crt: no such file or directory
time="2021-03-23T14:01:36Z" level=fatal msg="Unable to start server with TLS enabled. Cause: open /var/serving-cert/tls.crt: no such file or directory"
```
It seems that the volumes aren't being mounted properly. What we have is: 
```
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: workspacee053e71ddf0d42b6-sa-token-v4rpp
      readOnly: true
```

What we probably want is: 
```
    volumeMounts:
    - name: workspacee053e71ddf0d42b6-sa-token-v4rpp
      readOnly: true
      mountPath: /var/run/secrets/kubernetes.io/serviceaccount
    - name: workspace-serving-cert-workspacee053e71ddf0d42b6-service
      readOnly: true
      mountPath: /var/serving-cert/
```
