### ISSUE TITLE
Project clone does not handle checkoutFrom without origin even if there is only one remote configured

### ISSUE THREAD

**Issue by benoitf** [devfile/devworkspace-operator#443]
Hello,

maybe I'm wrong but if I use the following devfile https://github.com/che-samples/java-spring-petclinic/blob/devfilev2/devfile.yaml

which contains 
```yaml
projects:
  - name: spring-petclinic
    git:
      checkoutFrom:
        revision: devfilev2
      remotes:
        origin: "https://github.com/che-samples/spring-petclinic"
```

devWorkspace operator is reporting the error message

```
2021/06/03 13:57:09 failed to clone project spring-petclinic: project checkoutFrom refers to non-existing remote
```

but it seems it's a valid branch

```bash
$ git clone --branch devfilev2 https://github.com/che-samples/spring-petclinic                                                                                               
Cloning into 'spring-petclinic'...
remote: Enumerating objects: 8606, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 8606 (delta 0), reused 4 (delta 0), pack-reused 8601
Receiving objects: 100% (8606/8606), 7.28 MiB | 25.09 MiB/s, done.
Resolving deltas: 100% (3269/3269), done.
```

API is saying

```
remote: string
The remote name should be used as init. Required if there are more than one remote configured

revision: string 
The revision to checkout from. Should be branch name, tag or commit id. Default branch is used if missing or specified revision is not found.
```
