### ISSUE TITLE
failure to start a devWorkspace with low memoryLimit

### ISSUE THREAD

**Issue by benoitf** [devfile/devworkspace-operator#462]
Using the following devWorkspace, workspace is not starting

```
NAMESPACE   NAME      DEVWORKSPACE ID             PHASE      INFO
default     failure   workspace622225a967194e5b   Starting   Waiting for workspace deployment
```

devWorkspace to use:
```yaml
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: failure
spec:
  started: true
  template:
    components:
      - name: tools
        container:
          image: quay.io/eclipse/che-quarkus:next
          memoryLimit: 1G
      - name: ubi-minimal
        container:
          image: registry.access.redhat.com/ubi8/ubi-minimal
          command: ['tail']
          args: ['-f', '/dev/null']
          memoryLimit: 32M
```

Error is shown in devworkspace-controller pod:
```
spec.template.spec.containers[1].resources.requests: Invalid value: \"64M\": must be less than or equal to memory 
```

```
{"level":"info","ts":1624016878.2157364,"logger":"controllers.DevWorkspace","msg":"Waiting on deployment to be ready","Request.Namespace":"default","Request.Name":"failure","devworkspace_id":"workspace622225a967194e5b"}
{"level":"error","ts":1624016878.2306747,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"workspace.devfile.io","reconcilerKind":"DevWorkspace","controller":"devworkspace","name":"failure","namespace":"default","error":"Deployment.apps \"workspace622225a967194e5b\" is invalid: spec.template.spec.containers[1].resources.requests: Invalid value: \"64M\": must be less than or equal to memory limit","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:246\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:197\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:90"}
```

So it seems that if we specify memoryLimit to 32M, devWorkspace controller sets as memoryRequest 64M (I suspect it should in that case use the limit value)

And anyway, failure is not reported to 'end user'
