### ISSUE TITLE
Happy path tests don't use PR deployment templates

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#484]
### Description

The happy path test uses `chectl` to deploy the Che operator with DevWorkspaces support enabled. The only configuration applied to the CheCluster CR is:
```
+ cat /tmp/che-cr-patch.yaml
spec:
  devWorkspace:
    enable: true
    controllerImage: 'registry.build02.ci.openshift.org/ci-op-3z668v78/pipeline@sha256:322dc913cd574dbe5c2069f36452cac18c5fcaaaec1653173bfcfd5157fa0f2a'
```
where the controllerImage is the result of the CI build. 

This means any PR that needs to update deployment templates will fail the happy path test, as the test will deploy an updated image with stale templates.
