### ISSUE TITLE
Add support for defining environment variables for all containers in a component

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#530]
### Description

Since https://github.com/devfile/api/issues/149 will not be included in the Devfile 2.0 spec, we should consider supporting similar functionality via a controller-specific attribute on components. Some Che components (e.g. telemetry for the publicly hosted deployment) require the feature to function correctly, and reimplementing it as suggested in https://github.com/devfile/api/issues/239 is difficult.

#### 1. Implement workspaceEnv as global variables
This would require
1. A plugin to define a devfile 2.0 global variable, e.g.
    ```yaml
    template:
      variables:
        MY_ENV: "desired_value"
    ```
2. All plugins that expect to use the variable to have an environment variable defined
    ```yaml
    env:
      - name: MY_ENV
        value: "{{MY_ENV}}"
    ```

However, the dependent plugins from step 2 cannot assume that the variable will be provided. If the plugin from step 1 is not included in a DevWorkspace, the DevWorkspace will issue a warning that there's no replacement for `{{MY_ENV}}`.

#### 2. Implement workspaceEnv as an attribute
A plugin could define an attribute
```yaml
attributes:
  workspaceEnv:
    name: MY_ENV
    value: "desired_value"
```

This would signal the controller to add the env var `MY_ENV=desired_value` to all containers in the DevWorkspace. However, this would be DevWorkspace controller-specific behaviour and completely outside the Devfile 2.0 spec as it's currently written.
