### ISSUE TITLE
Drop web terminal from DWO

### ISSUE THREAD

**Issue by sleshchenko** [devfile/devworkspace-operator#565]
DWO currently has several references for Web Terminal:
1. plugin in the internal plugin registry, which we should drop and use in samples the actual config for Terminal:
```yaml
  template:
    components:
    - name: web-terminal-tooling
      plugin:
        kubernetes:
          name: web-terminal-tooling
          namespace: openshift-operators
    - name: web-terminal-exec
      plugin:
        kubernetes:
          name: web-terminal-exec
          namespace: openshift-operators
```

2. web terminal routing. Which is cheap to have in DWO but it's not part of DWO anymore... Ideally, we should need to extend DevWorkspace Routing Resolved from WTO and do web-terminal routing there, as Che Routing works. But it's something we may consider not worth doing ATM.

3. Remove config for web terminal https://github.com/devfile/devworkspace-operator/blob/main/pkg/config/cmd_terminal.go, https://github.com/devfile/devworkspace-operator/blob/main/pkg/library/flatten/web_terminal/web_terminal.go
