### ISSUE TITLE
Include ssh keys and tls certs into gitconfig

### ISSUE THREAD

**Issue by sleshchenko** [devfile/devworkspace-operator#613]
### Description
Currently, DWO generates gitconfig with personal access tokens, but it does not propagate SSH keys secrets, nor TLS certs.

**Comment by max-cx** [comment]
Hi, a question to the assignee of this issue:

Will the outcome require any changes to the relevant content of the _Installation Guide_ or _Administration Guide_ or _End-user Guide_?

Yes/No?

**Comment by JPinkney** [comment]
SSH support can be enabled by:
```bash
cat > /tmp/gitconfig <<EOF
host *
  IdentityFile /.ssh/id_rsa
  StrictHostKeyChecking = no
EOF

kubectl create secret generic git-ssh-key \
  --from-file=id_rsa=/path/to/private-key \
  --from-file=id_rsa.pub=/path/to/public-key \
  --from-file=config=/tmp/gitconfig

kubectl patch secret git-ssh-key --type merge -p \
  '{"metadata": {
     "labels": {
        "controller.devfile.io/mount-to-devworkspace": "true",
        "controller.devfile.io/watch-secret": "true"
      }, 
      "annotations": {
        "controller.devfile.io/mount-path": "/.ssh/"
      }
    }
  }'
```


TLS cert support can be enabled by:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: tls-configmap-test
  namespace: devworkspace-controller
  labels:
    "controller.devfile.io/git-tls-credential": "true"
    "controller.devfile.io/watch-configmap": "true"
  annotations:
    controller.devfile.io/mount-path: /home/theia/tls
data:
  host: https://github.com # this is optional, if its not set then the certificate will be applied to all git servers
  certificate: asdfasdfasdfasdfasdfasdfasdfasdf # this is the public certificate that you can download through your browser
```
