### ISSUE TITLE
Volume bound to a namespace and not a workspace

### ISSUE THREAD

**Issue by benoitf** [devfile/devworkspace-operator#630]
### Description
I would like to be able to get a volume that is bound to my user and not my workspace.
I would like to find my 'user files' in all workspaces

### Additional context
For example, pre-populate some volumes when creating the user namespace so data are already there when I need it inside a workspace

I may have 'read-only' mode or 'read-write' mode on those depending on the usecase

**Comment by amisevsk** [comment]
Formal support for this could be provided via https://github.com/devfile/api/issues/374 on the devfile/api side. As for the DevWorkspace Operator, we currently support auto-mounting existing volumes into all DevWorkspaces in a namespace via the automount labels:

* Label `controller.devfile.io/mount-to-devworkspace` defines a PVC as "should be mounted to DevWorkspaces"
* Annotation `controller.devfile.io/mount-path` defines the mount path within all containers where the PVC should be mounted
* Annotation `controller.devfile.io/read-only` defines if the PVC should be mounted read-only or not

**Comment by amisevsk** [comment]
The issue for documenting the annotations above is progressing: https://github.com/devfile/devworkspace-operator/issues/577

**Comment by benoitf** [comment]
@amisevsk 

so it seems it doesn't work if I want to use these attributes in the devfile.yaml (or a DevWorkspaceTemplate)

something like:

```yaml
    components:
      - name: user-data
        volume: {}
        attributes:
           "controller.devfile.io/something-to-say-i-want-a-user-volume": "user-data"
           "controller.devfile.io/mount-path": "/user-data"
```
