### ISSUE TITLE
Support user name and email in gitconfig

### ISSUE THREAD

**Issue by metlos** [devfile/devworkspace-operator#694]
### Description
To achieve feature parity with the Che server, DWO should support setting the user name and email in the git config.

For Devworkspace, it seems reasonable to use the same approach as with other parts of the git configuration and have a dedicated label for marking a config map with this information. E.g.

```yaml
kind: ConfigMap
metadata:
  labels:
    "controller.devfile.io/git-user-config": "true"
    "controllder.devfile.io/watch-configmap": "true"
data:
  name: Will E. Coyote
  email: wcoyote@acme.com
```

UPDATE:
This issue has the following subtasks:
- [x] Allow injecting gitconfigs using a configmap ([PR](https://github.com/devfile/devworkspace-operator/pull/710)) (part of milestone 3)
- [ ] Retrieving user email and name tasks (not part of milestone 3):
  - [ ] https://github.com/eclipse/che/issues/21115 
  - [ ] https://github.com/eclipse/che/issues/20937
  - [ ] https://github.com/eclipse/che/issues/20938
