### ISSUE TITLE
missing path in route endpoint

### ISSUE THREAD

**Issue by benoitf** [devfile/devworkspace-operator#713]
### Description
When defining a devfile, we can specify the path attribute like

```yaml
- name: my-endpoint
   attributes:
     type: main
   targetPort: 3100
   exposure: public
   path: '?my=path'
   secure: false
   protocol: https
```

but generate route is not adding ?my-path on the DW route

Using che routing, the path is correctly added

### How To Reproduce

```bash
kubectl apply -f https://eclipse-che.github.io/che-devfile-registry/main/devfiles/java-web-spring/devworkspace-che-code-insiders.yaml
```
and check the route

### Expected behavior
path is added on the URL of the main route
