### ISSUE TITLE
DevWorkspaces with async storage and ephemeral projects volume cannot start

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#730]
### Description
DevWorkspaces that use attribute `controller.devfile.io/storage-type: async` and explicitly define an ephemeral projects volume fail to start due to the projects volume being added twice.

### How To Reproduce
Create DevWorkspace
```yaml
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: theia-next
spec:
  started: true
  template:
    attributes:
      controller.devfile.io/storage-type: async
    projects:
      - name: web-nodejs-sample
        git:
          remotes:
            origin: "https://github.com/che-samples/web-nodejs-sample.git"
    components:
      - name: theia
        plugin:
          uri: https://che-plugin-registry-main.surge.sh/v3/plugins/eclipse/che-theia/next/devfile.yaml
          components:
            - name: theia-ide
              container:
                env:
                  - name: THEIA_HOST
                    value: 0.0.0.0
      - name: projects
        volume:
          ephemeral: true
```
