### ISSUE TITLE
Project clone fails to checkout revisions in large repos

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#739]
### Description
The project clone container fails to check out revisions in certain large repos, likely due to issues in `go-git`. Attempting to checkout a branch or commit in such a repo fails with error like:
```
2022/01/14 14:57:48 Encountered error while setting up project che-code: failed to checkout revision: failed to checkout commit 22c1cdbba0ff3b97eb7117859a18f4dc32cd0308: worktree contains unstaged changes
```

### How To Reproduce
Create DevWorkspace
```yaml
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: test-project-clone
spec:
  started: true
  template:
    projects:
    - git:
        checkoutFrom:
          revision: 60e69ce868b9b1ed821e7617878f644c0d898cc1
        remotes:
          origin: https://github.com/benoitf/che-code.git
      name: che-code
    components:
      - name: theia
        plugin:
          uri: https://che-plugin-registry-main.surge.sh/v3/plugins/eclipse/che-theia/next/devfile.yaml
          components:
            - name: theia-ide
              container:
                env:
                  - name: THEIA_HOST
                    value: 0.0.0.0

```
and check project-clone container logs

### Expected behavior
Checkout succeeds

### Additional context
Che issue: https://github.com/eclipse/che/issues/21025
