### ISSUE TITLE
As a user, I want to start a DevWorkspace based on the 2.2 sanples from https://registry.devfile.io/viewer

### ISSUE THREAD

**Issue by ibuziuk** [devfile/devworkspace-operator#752]
### Description
Openshift 4.10 is going to have devfile 2.2 samples 

![image](https://user-images.githubusercontent.com/1461122/150778894-b3bfa229-a7f5-4039-a0ba-de61d7068cad.png)

It should be possible to start the DevWorkspaces based on those samples.

### Additional context
Each of the samples contains the `outerloop-build` and `outerloop-deploy` (uses images from the `outerloop-build`) components: 

```
components:
  - name: outerloop-build
    image:
      imageName: nodejs-image:latest
      dockerfile:
        uri: Dockerfile
        buildContext: .
        rootRequired: false
  - name: outerloop-deploy
    kubernetes:
      uri: outerloop-deploy.yaml
```

DevWorkspace operator does not support dockerfile builds, so a workspace should be started based on the Universal Developer Image with the source code available after startup
