### ISSUE TITLE
Async storage sidecar is failing to sync files to server

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#754]
### Description
The async storage sidecar logs errors shortly after start, and is unable to sync data to the async storage server.

### How To Reproduce
Apply the DevWorkspace
```yaml
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: async-storage
spec:
  started: true
  template:
    attributes:
      controller.devfile.io/storage-type: async
    projects:
      - name: web-nodejs-sample
        git:
          remotes:
            origin: "https://github.com/che-samples/web-nodejs-sample.git"
    components:
      - name: theia
        plugin:
          uri: https://che-plugin-registry-main.surge.sh/v3/plugins/eclipse/che-theia/next/devfile.yaml
          components:
            - name: theia-ide
              container:
                env:
                  - name: THEIA_HOST
                    value: 0.0.0.0
    commands:
      - id: say-hello
        exec:
          component: theia-ide
          commandLine: echo "Hello from $(pwd)"
          workingDir: ${PROJECTS_ROOT}/project/app
```
and check logs in the async-storage-sidecar container.

### Additional context
<details>
  <summary>project-clone-sidecar logs</summary>

```
time="2022-01-24T20:27:39Z" level=info msg="read crontab: /etc/crontabs/backup-cron-job"
Failed to read the next line. Cause: EOFFailed to read the next line. Cause: EOF2022/01/24 20:28:04 exit status 23
time="2022-01-24T20:30:00Z" level=info msg=starting iteration=0 job.command=/scripts/backup.sh job.position=0 job.schedule="*/10 * * * *"
time="2022-01-24T20:30:00Z" level=info msg="Could not create directory '/.ssh'." channel=stderr iteration=0 job.command=/scripts/backup.sh job.position=0 job.schedule="*/10 * * * *"
time="2022-01-24T20:30:00Z" level=info msg="Warning: Permanently added '[async-storage]:2222,[172.30.243.202]:2222' (RSA) to the list of known hosts." channel=stderr iteration=0 job.command=/scripts/backup.sh job.position=0 job.schedule="*/10 * * * *"
time="2022-01-24T20:30:00Z" level=info msg="Could not create directory '/.ssh'." channel=stderr iteration=0 job.command=/scripts/backup.sh job.position=0 job.schedule="*/10 * * * *"
time="2022-01-24T20:30:00Z" level=info msg="Warning: Permanently added '[async-storage]:2222,[172.30.243.202]:2222' (RSA) to the list of known hosts." channel=stderr iteration=0 job.command=/scripts/backup.sh job.position=0 job.schedule="*/10 * * * *"
time="2022-01-24T20:30:00Z" level=info msg="rsync: recv_generator: mkdir \"/async-storage/projects/dev\" failed: Permission denied (13)" channel=stderr iteration=0 job.command=/scripts/backup.sh job.position=0 job.schedule="*/10 * * * *"
time="2022-01-24T20:30:00Z" level=info msg="*** Skipping any contents from this failed directory ***" channel=stderr iteration=0 job.command=/scripts/backup.sh job.position=0 job.schedule="*/10 * * * *"
time="2022-01-24T20:30:00Z" level=info msg="rsync: recv_generator: mkdir \"/async-storage/projects/devworkspace-metadata\" failed: Permission denied (13)" channel=stderr iteration=0 job.command=/scripts/backup.sh job.position=0 job.schedule="*/10 * * * *"
time="2022-01-24T20:30:00Z" level=info msg="*** Skipping any contents from this failed directory ***" channel=stderr iteration=0 job.command=/scripts/backup.sh job.position=0 job.schedule="*/10 * * * *"
time="2022-01-24T20:30:00Z" level=info msg="rsync: recv_generator: mkdir \"/async-storage/projects/etc\" failed: Permission denied (13)" channel=stderr iteration=0 job.command=/scripts/backup.sh job.position=0 job.schedule="*/10 * * * *"
time="2022-01-24T20:30:00Z" level=info msg="*** Skipping any contents from this failed directory ***" channel=stderr iteration=0 job.command=/scripts/backup.sh job.position=0 job.schedule="*/10 * * * *"
time="2022-01-24T20:30:00Z" level=info msg="rsync: recv_generator: mkdir \"/async-storage/projects/home\" failed: Permission denied (13)" channel=stderr iteration=0 job.command=/scripts/backup.sh job.position=0 job.schedule="*/10 * * * *"
time="2022-01-24T20:30:00Z" level=info msg="*** Skipping any contents from this failed directory ***" channel=stderr iteration=0 job.command=/scripts/backup.sh job.position=0 job.schedule="*/10 * * * *"
time="2022-01-24T20:30:00Z" level=info msg="rsync: recv_generator: mkdir \"/async-storage/projects/lib\" failed: Permission denied (13)" channel=stderr iteration=0 job.command=/scripts/backup.sh job.position=0 job.schedule="*/10 * * * *"
time="2022-01-24T20:30:00Z" level=info msg="*** Skipping any contents from this failed directory ***" channel=stderr iteration=0 job.command=/scripts/backup.sh job.position=0 job.schedule="*/10 * * * *"
time="2022-01-24T20:30:00Z" level=info msg="rsync: recv_generator: mkdir \"/async-storage/projects/media\" failed: Permission denied (13)" channel=stderr iteration=0 job.command=/scripts/backup.sh job.position=0 job.schedule="*/10 * * * *"
```

</details>
