### ISSUE TITLE
Attempting to start a DevWorkspace with projects but no container components fails

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#772]
### Description
Attempting to start a DevWorkspace like
```yaml
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: theia-next
spec:
  started: true
  template:
    projects:
      - name: web-nodejs-sample
        git:
          remotes:
            origin: "https://github.com/che-samples/web-nodejs-sample.git"
```
fails with misleading error
```
Deployment.apps "workspace5129321286cc409f" is invalid: [spec.template.spec.containers: Required value, spec.template.spec.initContainers[0].volumeMounts[0].name: Not found: "projects"]
```

The underlying issue is that the project-clone init container is added whenever there are projects defined in the spec, but since there are no containers, no volumes are provisioned to the workspace

### How To Reproduce
Start DevWorkspace above
