### ISSUE TITLE
Workspaces can fail to start on OpenShift when waiting for serving certificate from service-ca operator 

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#775]
### Description
With certain routingClasses (e.g. `cluster-tls` and `web-terminal`), the DevWorkspace Operator depends on the service-ca operator to [inject](https://docs.openshift.com/container-platform/4.9/security/certificates/service-serving-certificate.html) service certs into containers. This results in a volume being added to the pod:
```yaml
  - name: devworkspace-serving-cert-<workspaceID>-service
    secret:
      defaultMode: 420
      secretName: <workspaceID>-service
```

However, in some cases, it may take the cluster some time to create the secret referenced in this pod, resulting in the workspace failing to start due to the mounted volume not being found

### How To Reproduce
Create a *new* DevWorkspace with routingClass `cluster-tls`. It has to be a new (not existing) workspace as the second time starting the workspace will generally succeed as the secret has been created by that point. 

This issue does not reproduce consistently, but is more likely on larger/more loaded clusters.

### Expected behavior
DWO should ideally ignore volumeMount events when they concern the injected secret.

### Additional context
WTO Jira issue: https://issues.redhat.com/browse/WTO-123
