### ISSUE TITLE
Support components of type Kubernetes and OpenShift

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#798]
### Description
The Devfile API specifies Kubernetes and OpenShift component types, which consist mainly of raw Kubernetes/OpenShift yaml/json objects that should be applied to the cluster. These components are currently ignored by the DevWorkspace Operator, but should be supported -- at least at a "best effort" level (i.e. within DWO privileges and with limited syncing/cleanup)

### Additional context
Related to https://github.com/eclipse/che/issues/17894

**Comment by Bolodya1997** [comment]
@amisevsk 
Hello, is there any plan or progress for this issue?
It looks like this can be used to combine secrets automount and providing secrets via devfile:
```yaml
components:
  - name: git-credentials-gitlab
    kubernetes:
      inlined: |
        {
          "kind": "Secret",
          "apiVersion": "v1",
          "metadata": {
            "name": "git-credentials-gitlab",
            "annotations": {
              "controller.devfile.io/mount-path": "/home/theia/.git-credentials"
            },
            "labels": {
              "controller.devfile.io/git-credential": "true",
              "controller.devfile.io/watch-secret": "true"
            }
          },
          "type": "Opaque",
          "data": {
            "credentials": "aHR0cDovL...b2NhbA=="
          }
        }
```
Currently it doesn't look like there is a way to propagate secrets to the user namespace in a more or less automatic way without having admin access, so it will be extremely helpful if this would be implemented.
