### ISSUE TITLE
Project clone fails to checkout branch when revision specifies the default branch

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#806]
### Description
The project-clone init container will fail to checkout the branch for projects that define a `checkoutFrom` that uses the default branch as a revision.

Project clone will fail with error message e.g.
```
fatal: A branch named 'main' already exists.
```

### How To Reproduce
Create DevWorkspace
```yaml
cat <<EOF | kubectl apply -f -
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: plain
  annotations:
    controller.devfile.io/debug-start: "true"
spec:
  routingClass: basic
  started: true
  template:
    attributes:
      controller.devfile.io/storage-type: ephemeral
    projects:
      - name: devworkspace-operator
        git: 
          remotes:
            origin: 'https://github.com/devfile/devworkspace-operator.git'
            amisevsk: 'https://github.com/amisevsk/devworkspace-operator.git'
          checkoutFrom:
            remote: amisevsk
            revision: main
    components:
    - name: web-terminal
      container:
        command: ["tail", "-f", "/dev/null"]
        image: quay.io/amisevsk/web-terminal-tooling:dev
        memoryLimit: 512Mi
        mountSources: true
EOF
```

### Expected behavior
Project clone should check out the existing branch and update the tracking to match the expected remote
