### ISSUE TITLE
Project clone crashes if project `checkoutFrom` does not specify a revision

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#807]
### Description
The project-clone container will crash if a project specifies a `checkoutFrom` field but does not include a `revision`. In this case, the default branch for a given remote should be used. From the devfile documentation:

> revision: string
>
> The revision to checkout from. Should be branch name, tag or commit id. Default branch is used if missing or specified revision is not found.

### How To Reproduce
Create DevWorkspace
```yaml
cat <<EOF | kubectl apply -f -
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: plain
  annotations:
    controller.devfile.io/debug-start: "true"
spec:
  routingClass: basic
  started: true
  template:
    attributes:
      controller.devfile.io/storage-type: ephemeral
    projects:
      - name: devworkspace-operator
        git: 
          remotes:
            origin: 'https://github.com/devfile/devworkspace-operator.git'
            amisevsk: 'https://github.com/amisevsk/devworkspace-operator.git'
          checkoutFrom:
            remote: amisevsk
    components:
    - name: web-terminal
      container:
        command: ["tail", "-f", "/dev/null"]
        image: quay.io/amisevsk/web-terminal-tooling:dev
        memoryLimit: 512Mi
        mountSources: true
EOF
```

### Expected behavior
Project clone should use the default branch for the repo (e.g. `main`)

### Additional context
Devfile API reference: https://devfile.io/docs/devfile/2.1.0/user-guide/api-reference/
