### ISSUE TITLE
garbage collect stray instances

### ISSUE THREAD

**Issue by davidkarlsen** [devfile/devworkspace-operator#810]
### Description
stopped workspaces hang around and leave resources (replicasets, services, etc):
```
k get devworkspaces.workspace.devfile.io  -A
NAMESPACE            NAME              DEVWORKSPACE ID             PHASE     INFO
acg-prod             terminal-33wb5u   workspace32f75cd97a1640aa   Stopped   Stopped
openshift-terminal   terminal-pg4qld   workspacef9ef34e9774c46a9   Stopped   Stopped
pob-prod             terminal-e4btzu   workspace3ffeac06abb54fff   Stopped   Stopped
pob-prod             terminal-vxavla   workspaceffa5b194aa3a4475   Stopped   Stopped
srk-prod             terminal-7inev0   workspace580d39adba6b4b50   Stopped   Stopped
srk-prod             terminal-kq3rut   workspacef88e06ccd02b4d65   Stopped   Stopped
```

it would be good if these can be garbagecollected and removed in order to avoid cognitive overhead and obsolete resources in etcd and unnecessary load on iptables (for the services).

**Comment by amisevsk** [comment]
This is a great point. The DevWorkspace Operator currently supports this via the config option `.workspace.cleanupOnStop` in the DevWorkspaceOperatorConfig CR:

```yaml
apiVersion: controller.devfile.io/v1alpha1
kind: DevWorkspaceOperatorConfig
metadata:
  name: devworkspace-operator-config
  namespace: openshift-operators
config:
  workspace:
    cleanupOnStop: true
```
however this is a global setting and would impact all workspaces.

To resolve this issue, we should either (or both, likely)
1. Make `true` the default value for `cleanupOnStop`, since this could continue to be an annoyance
2. Add a way to configure it per-workspace and update the OpenShift Console to apply this configuration to web terminals
