### ISSUE TITLE
Automounted volumes can exceed name length limit

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#828]
### Description
DWO names automounted volumes with a prefix (e.g. `automount-configmap-<configmap-name>`>. However, if the configmap name is long, this can result in the volume name being longer than 63 characters, resulting in Workspace deployments being invalid.

### How To Reproduce
Create automount configmap
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-loooooooooooooooooooong-configmap-name
  labels:
    controller.devfile.io/mount-to-devworkspace: "true"
    controller.devfile.io/watch-configmap: 'true'
  annotations:
    controller.devfile.io/mount-as: file
    controller.devfile.io/mount-path: /tmp/configmap/file
data:
  configmap-key: "hello"
```
and attempt to start a workspace.

### Expected behavior
We likely need to change how we generate automounted volume names

### Additional context
Eclipse Che can run into this issue since it automatically uses automount functionality for some features.
