### ISSUE TITLE
Start a (default, configurable) Pod if the `DevWorkspace.spec.template` is empty

### ISSUE THREAD

**Issue by l0rd** [devfile/devworkspace-operator#853]
### Description

The simplest DevWorkspace is:

```yaml
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: devspaceworks
```

If I `kubectl apply -f -` the above DevWorkspace I would like to have a pre-defined workspace to be started. 
A pre-defined workspace may be specified in the `DevWorkspaceConfig`:

```diff
kind: DevWorkspaceOperatorConfig
apiVersion: controller.devfile.io/v1alpha1
metadata:
  name: devworkspace-operator-config
config:
  workspace:
+    defaultTemplate:
+      attributes:
+         controller.devfile.io/storage-type: ephemeral
+      components:
+        - name: frontend
+           container:
+             image: quay.io/devfile/universal-developer-image:ubi8-latest
+             memoryLimit: 1G
+             memoryRequest: 256Mi
+             cpuLimit: 500m
+             cpuRequest: 30m
```
