### ISSUE TITLE
Order of volumeMounts, etc. is not consistent in deployment, resulting in repeated changes

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#859]
### Description
Similar to https://github.com/devfile/devworkspace-operator/issues/849, DWO also has an issue when using subpath mounts, where the individual volume mounts can appear in a random order. This is because the internal comparison ignores order based on volume name, but for subpath volumes, we have multiple volumes for the same configmap

As DWO encounters these entries in random order, it causes random changes to the workspace deployment, preventing the workspace from starting.

### How To Reproduce
Apply the configmap
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-scripts
  annotations:
    controller.devfile.io/mount-as: subpath
    controller.devfile.io/mount-path: /home/user/
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-configmap: 'true'
data:
  init-nodejs.sh: 'test'
  init-truststore.sh: 'test'
```
and attempt to start a workspace.
