### ISSUE TITLE
Incorrect proxy settings read when proxy specified in dwoc at start

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#865]
### Description
Normally, on OpenShift, DWO reads the cluster proxy object on OpenShift to automatically configure the proxy used for both itself and workspaces. However, if the DevWorkspaceOperatorConfig proxy settings are not empty, DWO does not merge the cluster config and its own config at startup, resulting in only the DevWorkspaceOperatorConfig proxy settings being used.

This persists until the DevWorkspaceOperatorConfig is edited again, at which point the two are merged correctly and the proxy functions as intended.

### How To Reproduce
Create the DevWorkspaceOperatorConfig in an OpenShift cluster with a proxy configured
```yaml
apiVersion: controller.devfile.io/v1alpha1
kind: DevWorkspaceOperatorConfig
metadata:
  name: devworkspace-operator-config
config:
  routing:
    proxyConfig:
      noProxy: "test.no-proxy.com"
```
On startup, note that DWO logs 
```
{"level":"info","ts":1654788202.0073922,"logger":"operator-configuration","msg":"Resolved proxy configuration","proxy":{"noProxy":"test.no-proxy.com"}}
```
ignoring whatever cluster settings are present. If you edit the DevWorkspaceOperatorConfig later, DWO will log the correct object, merging the cluster config and additional config.

### Expected behavior
The two configs should be merged.
