### ISSUE TITLE
StorageError sometimes logged when deleting a DevWorkspace

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#878]
### Description
I've noticed on some occasions that DWO logs an error like
```yaml
# Note: reformatted to yaml from the JSON for readability
level: error
ts: 1656381116.590004
logger: controller-runtime.manager.controller.devworkspace
msg: Reconciler error
reconciler group: workspace.devfile.io
reconciler kind: DevWorkspace
name: theia-next-2
namespace: dw
error: 'Operation cannot be fulfilled on devworkspaces.workspace.devfile.io "theia-next-2":
  StorageError: invalid object, Code: 4, Key: /registry/workspace.devfile.io/devworkspaces/dw/theia-next-2,
  ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition:
  8d45666d-a151-4d72-8f92-0521641d25a7, UID in object meta: '
stacktrace: '[...]'
```
immediately after the `PVC clean up successful; clearing finalizer` message

### How To Reproduce
Occurs sometimes after deleting a DevWorkspace

### Expected behavior
Ideally error should not be logged as it may be confusing (and is not really an error case -- the workspace is gone so we don't care about its status)
