### ISSUE TITLE
Automounted gitconfig overwrites existing git config for project clone

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#911]
### Description
In the project-clone container, we install git-lfs to get support for Git Large File Storage in DWO. To enable git-lfs, the install updates `/etc/gitconfig` to contain
```
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
```

However, when an automounted gitconfig is used, this block is overwritten, breaking git-lfs for workspaces in that namespace.

### How To Reproduce
1. Create a configmap
    ```yaml
    apiVersion: v1
    kind: ConfigMap
    metadata:
      annotations:
        controller.devfile.io/mount-as: subpath
        controller.devfile.io/mount-path: /etc/
      labels:
        controller.devfile.io/mount-to-devworkspace: "true"
        controller.devfile.io/watch-configmap: "true"
      name: test-gitconfig
    data:
      gitconfig: |
        [user]
          name = hello
          email = world
    ```
2. Attempt to start a workspace that uses https://github.com/Apress/repo-with-large-file-storage.git
    ```yaml
    kind: DevWorkspace
    apiVersion: workspace.devfile.io/v1alpha2
    metadata:
      name: plain-devworkspace
    spec:
      started: true
      routingClass: basic
      template:
        projects:
          - name: repo-with-large-file-storage
            git:
              remotes:
                origin: 'https://github.com/Apress/repo-with-large-file-storage.git'
        components:
          - name: web-terminal
            container:
              image: quay.io/wto/web-terminal-tooling:next
              memoryLimit: 512Mi
              mountSources: true
              command:
              - "tail"
              - "-f"
              - "/dev/null"
    ```

### Expected behavior
Git-lfs correctly clones the `LargeFile.zip` file in that repo (should be ~200MB)
