### ISSUE TITLE
Support overriding arbitrary fields in workspace deployment's containers via attribute

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#945]
### Description
Add attribute `container-overrides` which can be applied to container components to specify container fields not available in the DevWorkspace spec. This would allow, for example, users to specify extended resources for container components, which are currently not available in the API:
```yaml
components:
  - name: go
    attributes:
      container-overrides: {"resources":{"limits":{"nvidia.com/gpu": "1"}}}
    container:
      image: ...
```

### Additional context
See discussion in devfile/api: https://github.com/devfile/api/issues/920
Follow up to https://github.com/devfile/devworkspace-operator/pull/944
