### ISSUE TITLE
kustomize 4.5.7 does not render namespaces in subjects of rolebinding and clusterrolebinding

### ISSUE THREAD

**Issue by vishaltak** [devfile/devworkspace-operator#971]
### Description
While trying to install devworkspace-operator, I realized that [`kustomize 4.0.5` used in the scripts](https://github.com/devfile/devworkspace-operator/blob/main/deploy/generate-deployment.sh#L129) is not available on M1 mac. When I change it to the latest version `4.5.7`, the generated resources at `./deploy/current/kubernetes/combined.yaml` and `./deploy/current/openshift/combined.yaml` have some resources(`RoleBinding` and `ClusterRoleBinding`) where the `namespace` for the `subjects` is not patched to the `OPERATOR_NAMESPACE`.

This causes the controller to be crashloopbackoff as it does not have the correct permissions.

Example of wrongly rendered resources -

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
  name: devworkspace-controller-leader-election-rolebinding
  namespace: devworkspace-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devworkspace-controller-leader-election-role
subjects:
- kind: ServiceAccount
  name: devworkspace-controller-serviceaccount
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
  name: devworkspace-controller-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devworkspace-controller-proxy-role
subjects:
- kind: ServiceAccount
  name: devworkspace-controller-serviceaccount
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
  name: devworkspace-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devworkspace-controller-role
subjects:
- kind: ServiceAccount
  name: devworkspace-controller-serviceaccount
  namespace: system
---
```

### How To Reproduce
1. Go to https://github.com/devfile/devworkspace-operator/blob/main/deploy/generate-deployment.sh#L129 and change version to `4.5.7`
2. Follow steps at https://github.com/devfile/devworkspace-operator#with-yaml-resources
3. Search for `namespace: system` in `./deploy/current/kubernetes/combined.yaml` and `./deploy/current/openshift/combined.yaml`

### Expected behavior
The `namespace` in the `RoleBinding` and `ClusterRoleBinding` should be patched to the correct value represented by `OPERATOR_NAMESPACE`.

### Additional context
https://github.com/kubernetes-sigs/kustomize/pull/4704
https://github.com/kubernetes-sigs/kustomize/issues/880
