### ISSUE TITLE
Hack 'n Hustle: command line tool to update a DevWorkspace

### ISSUE THREAD

**Issue by l0rd** [devfile/devworkspace-operator#990]
The goal is to create a small command line utility that takes as input the path to a devfile.yaml file and the path to a devworkspace.yaml file. As a result it prints to stdout a DevWorkspace object, identical to the original one, but with the template replaced by the Devfile content (with a few gotchas).

```bash
$ dw-update --help
Takes as input the path to a devfile.yaml file and the path to a devworkspace.yaml file and prints to stdout a DevWorkspace object, identical to the original one, but with the template replaced by the Devfile content (with a few gotchas).

Usage:
  dw-update [options]

Options:
  -d, --devfile=[]:
    The file that contains the new devfile that is going to be applied.
  -w, --devworkspace=[]:
    The file that contains the original DevWorksapce object, in YAML format.
```

The gotchas:

1) The original DevWorkspace `spec.template.projects` is not replaced (needed until eclipse/che/issues/21188)
2) An existing `controller.devfile.io/merge-contribution: true` attribute in the original DevWorkspace `spec.template.components` should be kept even if not present in the devfile (needed until devfile/devworkspace-operator/issues/993).

**Comment by AObuchow** [comment]
@l0rd I wanted to clarify about gotcha #2
> 2. An existing controller.devfile.io/merge-contribution: true attribute in the original DevWorkspace spec.template.components should be kept even if not present in the devfile.

Should only the attribute be kept? Or the entire component?

For example, do we want the following behaviour?

Given this devworkspace:
```YAML
Kind: Devworkspace
Spec:
  Template:
    Components:
      - name: componentA
        attributes:
          controller.devfile.io/merge-contribution: true
      - name: componentB
        attributes:
          controller.devfile.io/merge-contribution: true
```
And this devfile:

``` YAML
Kind: Devfile
Spec:
  Components:
     - name: ComponentB
```

The resulting devworkspace:
```YAML
Kind: Devworkspace
Spec:
  Template:
    Components:
      - name: componentB
        attributes:
          controller.devfile.io/merge-contribution: true
```
 
Or do we want this behaviour:

Given this devworkspace:
```YAML
Kind: Devworkspace
Spec:
  Template:
    Components:
      - name: componentA
        attributes:
          controller.devfile.io/merge-contribution: true
      - name: componentB
        attributes:
          controller.devfile.io/merge-contribution: true
```
And this devfile:

``` YAML
Kind: Devfile
Spec:
  Components:
     - name: ComponentB
```

The resulting devworkspace (`componentA` is kept because it has the `controller.devfile.io/merge-contribution:` true attribute):
```YAML
Kind: Devworkspace
Spec:
  Template:
    Components:
      - name: componentA
        attributes:
          controller.devfile.io/merge-contribution: true
      - name: componentB
        attributes:
          controller.devfile.io/merge-contribution: true
```
